hourCinderella = {
    "lineCount": 36, 
    0: {"en": "", "jp":"", "time": 150},
    1: {"en": "sunao ni I LOVE YOU!", "jp":"素直に I LOVE YOU!", "time": 75},
    2: {"en": "todokeyou ", "jp":"届けよう", "time": 35},
    3: {"en": "kitto YOU LOVE ME!", "jp":"きっとYOU LOVE ME!", "time": 55},
    4: {"en": "tsutawaru sa ", "jp":"伝わるさ", "time": 40},
    5: {"en": "kimi ni niau GLASS no", "jp":"キミに似合うガラスの", "time": 110},
    6: {"en": "kutsu wo sagasou", "jp":"靴を探そう", "time": 65},
    7: {"en": "futari de STEP & GO!", "jp":"2人でStep＆Go!", "time": 75},
    8: {"en": "itsu made mo", "jp":"いつまでも", "time": 35},
    9: {"en": "shinya juuniji wo sugitatte ", "jp":"深夜12時をすぎたって", "time": 95},
    10: {"en": "bokura no LOVE MAGIC wa", "jp":"ボクらの恋魔法-ラブマジック-は", "time": 100},
    11: {"en": "toke wa shinai", "jp":"解けはしない", "time": 105},
    12: {"en": "", "jp":"", "time": 15},
    13: {"en": "oide meshimase ohime-sama", "jp":"おいでめしませ　お姫様", "time": 150},
    14: {"en": "doku no ringo wo", "jp":"毒のリンゴを", "time": 105},
    15: {"en": "tabete nemucchai sou na", "jp":"食べて眠っちゃいそうな", "time": 120},
    16: {"en": "sunao sugiru kimi ga", "jp":"素直すぎるキミが", "time": 120},
    17: {"en": "totemo itoshii", "jp":"とても愛しい", "time": 120},
    18: {"en": "", "jp":"", "time": 40},
    19: {"en": "atarimae ＝-iko- takaramono sa", "jp":"当たり前＝-イコ-宝物さ", "time": 195},
    20: {"en": "chikyuu wa mawari hi wa nobori", "jp":"地球はまわり　陽はのぼり", "time": 170},
    21: {"en": "kimi wa hohoemu", "jp":"キミは微笑む", "time": 165},
    22: {"en": "", "jp":"", "time": 25},
    23: {"en": "sunao ni I LOVE YOU!", "jp":"素直に I LOVE YOU!", "time": 75},
    24: {"en": "todokeyou ", "jp":"届けよう", "time": 35},
    25: {"en": "kitto YOU LOVE ME!", "jp":"きっとYOU LOVE ME!", "time": 55},
    26: {"en": "tsutawaru sa ", "jp":"伝わるさ", "time": 40},
    27: {"en": "kimi ni niau GLASS no", "jp":"キミに似合うガラスの", "time": 110},
    28: {"en": "kutsu wo sagasou", "jp":"靴を探そう", "time": 65},
    29: {"en": "futari de STEP & GO!", "jp":"2人でStep＆Go!", "time": 75},
    30: {"en": "itsu made mo", "jp":"いつまでも", "time": 35},
    31: {"en": "shinya juuniji wo sugitatte ", "jp":"深夜12時をすぎたって", "time": 95},
    32: {"en": "kimi wa boku no itoshii", "jp":"キミは僕の愛しい", "time": 105},
    33: {"en": "nijuuyojikan CINDERELLA", "jp":"24時間シンデレラ", "time": 200},
    34: {"en": "HEY! HEY! HEY!", "jp":"HEY! HEY! HEY!", "time": 75},
    35: {"en": "", "jp":"", "time": 30},
    };

 


