var bakaMitai = {
    "lineCount": 21, 
    0: {"en": "", "jp":"", "time": 440},
    1: {"en": "baka mitai kodomo na no ne", "jp":"馬鹿みたい 子供なのね", "time": 180},
    2: {"en": "yume wo otte kizu tsuite", "jp":"夢を追って傷ついて", "time": 210},
    3: {"en": "uso ga heta na kuse ni", "jp":"嘘が下手なくせに", "time": 180},
    4: {"en": "waraenai egao miseta", "jp":"笑えない笑顔みせた", "time": 170},
    5: {"en": "", "jp":"", "time": 55},
    6: {"en": "I LOVE YOU mo", "jp":"I LOVE YOUも", "time": 75},
    7: {"en": "roku ni iwanai", "jp":"ろくに言わない", "time": 110},
    8: {"en": "kuchibeta de honma ni bukiyou", "jp":"口下手でほんまに不器用", "time": 165},
    9: {"en": "", "jp":"", "time": 45},
    10: {"en": "na no ni na no ni doushite", "jp":"なのになのにどうして", "time": 175},
    11: {"en": "sayonara wa ieta no", "jp":"サヨナラは言えたの", "time": 180},
    12: {"en": "dame da ne", "jp":"だめだね", "time": 65},
    13: {"en": "dame yo dame na no yo", "jp":"だめよ だめなのよ", "time": 135},
    14: {"en": "anta ga suki de", "jp":"あんたが 好きで", "time": 90},
    15: {"en": "suki sugite", "jp":"好きすぎて", "time": 105},
    16: {"en": "dore dake", "jp":"どれだけ", "time": 55},
    17: {"en": "tsuyoi osake de mo", "jp":"強いお酒でも", "time": 150},
    18: {"en": "yugamanai omoide ga", "jp":"歪まない思い出が", "time": 180},
    19: {"en": "baka mitai", "jp":"馬鹿みたい", "time": 60},
    20: {"en": "", "jp":"", "time": 690}
};