var judgement = {
    "lineCount": 21, 
    0: {"en": "", "jp":"", "time": 400},
    1: {"en": "RAIL kara hazureta", "jp": "レールからはずれた", "time": 185}, 
    2: {"en": "furyouhin no norainu sa", "jp": "不良品の野良犬さ", "time": 170}, 
    3: {"en": "dakedo kantan ni wa", "jp": "だけど簡単には", "time": 165}, 
    4: {"en": "TAIL wa furanai ze", "jp": "テールは振らないぜ", "time": 180}, 
    5: {"en": "", "jp": "", "time": 70}, 
    6: {"en": "YES MAN ni", "jp": "大人-イエスマン-に", "time": 85}, 
    7: {"en": "narisobireta", "jp": "成りそびれた", "time": 75}, 
    8: {"en": "(woah oh oh, woah oh, we are bad boys)", "jp": "(woah oh oh, woah oh, we are bad boys)", "time": 210}, 
    9: {"en": "waru ni nokosareta", "jp": "若者-ワル-に残された", "time": 135}, 
    10: {"en": "NO to iu na no", "jp": "「No」という名の", "time": 140}, 
    11: {"en": "JUSTICE", "jp": "JUSTICE", "time": 45}, 
    12: {"en": "WOW, BREAKIN' THE LAW", "jp": "WOW, BREAKIN' THE LAW", "time": 95}, 
    13: {"en": "BREAKIN’ THE WORLD kowase", "jp": "BREAKIN’ THE WORLD 壊せ", "time": 195}, 
    14: {"en": "kirisake TENDERNESS", "jp":"切り裂け TENDERNESS", "time": 70},
    15: {"en": "WOW, BREAKIN' THE RULE", "jp":"WOW, BREAKIN' THE RULE", "time": 110},
    16: {"en": "roppou zensho ja shibarenai", "jp":"六法全書じゃ縛れない", "time": 185},
    17: {"en": "hanran bunshi sa", "jp":"反乱分子さ", "time": 95},
    18: {"en": "furiageta nigiri kobushi ga", "jp":"振り上げた握り拳が", "time": 170},
    19: {"en": "oretachi no JUDGEMENT", "jp":"俺達のJUDGEMENT", "time": 125},
    20: {"en": "", "jp":"", "time": 165},
};